services:
  traefik:
    extends:
      file: ../../infra/traefik/docker-compose.yml
      service: traefik
      env_file:
        - ../../infra/traefik/.env

networks:
  pfsense-vlan:
    external: true      