version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_EMAIL_ADDRESS=${CF_EMAIL_ADDRESS}
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.httpss.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=${CF_EMAIL_ADDRESS}"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    #   - ./config/acme.json:/etc/traefik/acme.json
      - ./logs:/var/log/traefik
      - traefik-acme:/etc/traefik
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.portainer.stack.deploy=true"

      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.idp.labops.uk`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.idp.labops.uk`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=idp.labops.uk"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.idp.labops.uk"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      pfsense-vlan:
        ipv4_address: 172.20.60.43

networks:
  pfsense-vlan:
    external: true

volumes:
  traefik-acme:    